### ISSUE TITLE
Saving an object 2+ times resets it?

### ISSUE THREAD

**Issue by jonnyijapan** [gibtang/CCNSCoding#2]
I extended the HelloProject sample by adding a button in the middle of screen, an extra internal integer, and a label that increases for every button push. I call the save feature (the save paragraph from the constructor put into its own function) after the button push.

On load, it also loads the extra integer and refreshes the label, to show the number of button pushes so far.
For some reason this only works if I only tap the button once. If I tap the button twice, the output LocalData file seems to end up corrupted/empty. I'm wondering if this is a problem with CCNSEncoder class, or if I made some mistake.

Here's the code I use:

https://gist.github.com/jonnyijapan/d79814f7b867ab5fe1f2

**Comment by IgorVovk** [comment]
Probably I know what the reason of this issue, if you want to save the same object two times you have to execute:

``` c++
object_to_be_saved->resetSavedState();
```

right before calling saveToFile()

Because NSCoder will mark object if it has been saved to prevent saving it twice. E.g. if you added the same object into two different arrays and saving this arrays so both of arrays should have a reference to the single object instead of saving it twice. 
So in your case you have to do next: 

``` c++
void HelloWorld::menuButton(Object* pSender)
{
    test_buttonpushcount++;
    this->resetSavedState();
    this->save();   
    this->refreshbuttoncountlabel();
}
```

Thanks.

**Comment by jonnyijapan** [comment]
Thanks a lot. I tested it and it works. I often use the "save" function as a common pattern in my model classes. Whenever something changes for a user, maybe the amount of money he has, I add the money to the variable and then save right after. Has worked great so far :-). I guess an important thing is to watch out if the save method is called a bit too often or if it takes a long time etc but I had no problem so far. Anyway I didn't have to optimize anything concerning that so far.

Of course I am using NSCoding extensively in iOS since Cocos2D-iPhone/SpriteBuilder, and was really missing that feature when starting out with Cocos2D-x a while ago. I just don't understand how people save their stuff. I didn't find anything resembling NSUSerDefault so far anyway.
If I can use the same pattern as NSCoding, things would be much easier, and you also went the extra mile of saving/loading using json to disk. Perfect. Well that's the backside story and I guess that's the whole point of this great class.

With that said I can understand the feature to not save an object twice if it has not changed, but if it has changed we must still be able to save it again?

Also just an idea, but I think it's better to save to NSLibrary... I mean, some apps need to use the documents folder with desktop iTunes to transfer files, in those cases the files saved by this class will be very visible to Average Joe. I will probably change to use NSLibrary instead. It will be backed up etc too.
