### ISSUE TITLE
Saving vector with objects

### ISSUE THREAD

**Issue by jonnyijapan** [gibtang/CCNSCoding#3]
Being really rusty on C++, haven't used for like 10 years, but I fail at saving a vector with objects. Ie it's a std::vector<Myobject>.

I see that this class can save vectors with pointers to object, like std::vector<Myobject*> would work, provided Myobject inherits from `CCNSEncodableObject` and implements initWithCoder etc..?

So in the encode function I use another vector taking those pointers, and pushes pointers to the real objects into it, and then have that encoded - I guess this process would incur some performance penalty. I don't know if this is the intended use or not, but the save crashes on line 150 in CCNSCoder.cpp (`obj->encodeWithCoder(this);`), and I'm feeling I'm doing something wrong.

**Comment by IgorVovk** [comment]
I still working on CCNSCoder demo so for now I just can help you by sending some examples of using CCNSCoder (saving/reading objects, vectors, etc). 

https://drive.google.com/file/d/0B9QkIenAZZdYMUI2anlCQUdEcWc/view

Hopefully I'll come with latest code and extended explanation/examples soon.

**Comment by jonnyijapan** [comment]
Thanks. Your sample code saves vectors with strings... I am trying to save vectors with objects made by classes that inherit from CCNSEncodableObject. I have been able to save just one of those objects when it's just a normal class member, not in a vector. When it's a vector with many of those, it still crashes on line 150. I guess I will try to debug CCNSCoder but I don't really understand how everything works yet. I'll send the sample classes I use soon.

**Comment by jonnyijapan** [comment]
Here is the code... https://gist.github.com/jonnyijapan/5225f954377a9f768921 

It will (probably) crash in CCNSCoder.cpp on line 150 because of saving the vector "manyobjects" which is part of the class Mytestclass.

**Comment by jonnyijapan** [comment]
I think I might have found my error... I was defining "manyobjects" like this
`std::vector<Myinternalclass> manyobjects;`

And I guess keeping Myinternalclass objects on the stack does not work down the line, for some reason I just can't remember... like going out of focus.

So I changed to

```
std::vector<Myinternalclass*> manyobjects;
```

so I have to use `new` and all that and keep track of those objects. I guess this is the intended way to use this library. I don't reaaally remember such parts of C++ :-(

**Comment by IgorVovk** [comment]
That's how do I did it:
Saving:

``` c++
// allocate new vector and copy all items from other vector 
std::vector<CCNSEncodableObject > vec_lvl = new std::vector<CCNSEncodableObject*>m_level_data_object.begin(), m_level_data_object.end());
// save new vector
encoder->encodeVectorOfObjectsForKey(vec_lvl, "GameLevelData");
// delete currently allocated vector 
delete vec_lvl;
```

Vector m_level_data_object can contain object of any type but should be derived from CCNSEncodableObject. So functions encodeWithCoder will be called for each object in the vector.

Reading:

``` c++
// create vector with real type of objects
m_level_data_object = std::vector<LevelDataObject *>();
// create vector for reading with type of CCNSEncodableObject
std::vector<CCNSEncodableObject > vec_lvl;
// read to vector with CCNSEncodableObject type but 'real' type will be LevelDataObject
vec_lvl = decoder->decodeVectorOfObjectsForKey("GameLevelData");
// copy from vector with CCNSEncodableObject to vector with real type
for (CCNSEncodableObject obj : vec_lvl)
        m_level_data_object.push_back((LevelDataObject *)obj);
```

While reading for each LevelDataObject object will call initWithCoder.

Let me know if you have any other questions.

**Comment by jonnyijapan** [comment]
Ok thanks I think that's similar to how I ended up writing it. My next task will be to support map<type, type> things, similar to dictionaries. Currently that structure cannot be encoded right?

**Comment by IgorVovk** [comment]
No unfortunately saving function for std::map didn't implemented yet, probably I will do that in future as I'm using CCNSCoder for each cocos2dx project. 
I think you can give it a try by separating map into two vectors: keys and values and save it in this way.
But most important update for CCNSCoder should be encryption of result file as now it represented as human readable JSON so user can edit it which is really unwanted.

**Comment by jonnyijapan** [comment]
I needed to save `std::map<int, int>`.
I could not manage to save that as two vectors containing ints... until changed I that two vectors containing strings. So I needed to convert all ints to std::strings, and then save those. I guess there will be some overhead, but I've yet to see how performance plays out. Because after awhile although this seems to work at first, I see very frequent crashes in CCNSCoder.cpp on this line:

`str.append(cstr::stringWithFormat("\"%s\"", (((std::string *)it->second)[i]).c_str()));`

That's around line 297, where it works on string_array_values. The maps I use usually "work" save fine the first few times, but when the values amount to like 5 or above it just crashes hard on that line.

These are the stock functions I use to save/load int,int maps:

```
void savemap(CCNSCoder* encoder, std::map<int,int>* mappointer, std::string keyKeys, std::string keyValues) {
    CCLOG("savemap %s/%s (%ld values)", keyKeys.c_str(), keyValues.c_str(), mappointer->size());
    std::map<int,int> map = *mappointer;
    const int COUNT = (int)map.size();
    if (COUNT > 0) {
        std::vector<std::string> tempkeys;
        std::vector<std::string> tempvalues;

        CCLOG("saving to %s and %s:", keyKeys.c_str(), keyValues.c_str());

        std::string stringKey, stringValue;

        for (auto pair: map) {
            CCLOG("key %d has value %d", pair.first, pair.second);

            stringKey = std::to_string(pair.first);
            stringValue = std::to_string(pair.second);

            tempkeys.push_back(stringKey);
            tempvalues.push_back(stringValue);
        }
        encoder->encodeVectorForKey(&tempkeys, keyKeys);
        encoder->encodeVectorForKey(&tempvalues, keyValues);
    }
    else {
        CCLOG("No values!");
    }
}
void loadmap(CCNSCoder* decoder, std::string keyKeys, std::string keyValues, std::map<int, int>* mappointer) {
    CCLOG("loadmap %s/%s", keyKeys.c_str(), keyValues.c_str());

    std::vector<std::string> keys = decoder->decodeVectorOfStringsForKey(keyKeys);
    std::vector<std::string> values = decoder->decodeVectorOfStringsForKey(keyValues);

    const int COUNT_KEYS = (int)keys.size();
    const int COUNT_VALUES = (int)values.size();
    if (COUNT_KEYS != COUNT_VALUES) {
        CCLOGERROR("Keys and values size are not same! %s and %s", keyKeys.c_str(), keyValues.c_str());
        assert(false && "Keys and values counts were not same!");
    }
    else if (COUNT_KEYS == 0) {
        // Don't do anything... no data yet.
        CCLOG("No values!");
    }
    else {
        std::map<int, int> map = *mappointer;

        std::string stringKey, stringValue;
        int key, value;

        CCLOG("COUNT_KEYS: %d", COUNT_KEYS);

        for (int i = 0; i < COUNT_KEYS; i++) {
            stringKey = keys[i];
            stringValue = values[i];

            if (stringKey.length() == 0) {
                CCLOGERROR("length of key was 0!");
                continue;
            }
            if (stringValue.length() == 0) {
                CCLOGERROR("length of value was 0!");
                continue;
            }
            CCLOG("stringKey: '%s' (length: %lu), stringValue: '%s' (length: %lu)", stringKey.c_str(), stringKey.length(), stringValue.c_str(), stringValue.length());

            key = std::stoi(stringKey);
            value = std::stoi(stringValue);

            map[key] = value;

            CCLOG("key %d has value %d", key, map[key]);
        }
    }
}

```

**Comment by IgorVovk** [comment]
Hmm, weird that you can't save int values, it's easy as 

``` c++
encoder->encodeVectorForKey(m_idle_speed_values, "IdleSpeedValues");
```

where m_idle_speed_values is

``` c++
std::vector<double> *m_idle_speed_values;
```

Reading is pretty simple as well

``` c++
// read in tmp vector
std::vector<double> vec = decoder->decodeVectorForKey<std::vector<double>>("IdleSpeedValues");
// allocate new vector in memory and copy digits into it as vec is object allocated by decodeVectorForKey and will be released when running out of current function
m_idle_speed_values = new std::vector<double>(vec);
```

I think you have a problems with memory management, can you share full sources with me so I can debug it? 
Thanks.

**Comment by jonnyijapan** [comment]
I ended up using just a long comma-separated string like "1,3,4,5,3" for the keys, and then another one for the values yesterday.
Today I looked at the code above and I think I found my mistake.
For instance, I was doing `std::map<int, int> map = *mappointer;` in loadmap, because I thought it would be easier to access the map that way, turned out `map` ended up as another object than the one passed it. I just commented that line out and accessed `mappointer` directly using the arrow and so on. These are parts of C++ I really don't remember :-P.

Still I haven't tried your method above. Will try next time I run into it. Thanks.

Anyway I already got object save working so I guess I will close this issue for now.

Btw I agree with that there might be a need to save data less readable than json... I don't know if encrypting the json itself is the way to go, but in any case that could be made an option so each dev can choose that by himself? Anyway it's very useful to be able to double-check the saved data while developing. Also some apps might actually want to allow users to access their saved data settings etc. Like game level editors and so on.
On the generic side, I think it would be nice to follow the API of NSCoding as much as possible. With NSCoding we can just save NSArrays and NSDictionaries like any other object. It would be nice if CCNSCoding could do the same... I'm not sure that is possible with C++, we can't add categories etc ontop of std::vector and such anyway right...
 Just some ideas...

**Comment by jonnyijapan** [comment]
FWIW, these are the fixed static functions I added to CCNSCoder to be able to save std::map<int,int>:

```
void CCNSCoder::savemap(CCNSCoder* encoder, std::map<int,int>* mappointer, std::string keyKeys, std::string keyValues) {
    CCLOG("savemap %s/%s (%ld values)", keyKeys.c_str(), keyValues.c_str(), mappointer->size());
    //std::map<int,int> map = *mappointer;
    const int COUNT = (int)mappointer->size();
    if (COUNT > 0) {
        std::vector<std::string> tempkeys;
        std::vector<std::string> tempvalues;

        CCLOG("saving to %s and %s:", keyKeys.c_str(), keyValues.c_str());

        std::string stringKey, stringValue;

        for (auto pair: *mappointer) {
            //CCLOG("key %d has value %d", pair.first, pair.second);

            stringKey = std::to_string(pair.first);
            stringValue = std::to_string(pair.second);

            tempkeys.push_back(stringKey);
            tempvalues.push_back(stringValue);
        }
        encoder->encodeVectorForKey(&tempkeys, keyKeys);
        encoder->encodeVectorForKey(&tempvalues, keyValues);
    }
    else {
        CCLOG("No values!");
    }
}
void CCNSCoder::loadmap(CCNSCoder* decoder, std::string keyKeys, std::string keyValues, std::map<int, int>* mappointer) {
    CCLOG("loadmap %s/%s", keyKeys.c_str(), keyValues.c_str());

    std::vector<std::string> keys = decoder->decodeVectorOfStringsForKey(keyKeys);
    std::vector<std::string> values = decoder->decodeVectorOfStringsForKey(keyValues);

    const int COUNT_KEYS = (int)keys.size();
    const int COUNT_VALUES = (int)values.size();
    if (COUNT_KEYS != COUNT_VALUES) {
        CCLOGERROR("Keys and values size are not same! %s and %s", keyKeys.c_str(), keyValues.c_str());
        assert(false && "Keys and values counts were not same!");
    }
    else if (COUNT_KEYS == 0) {
        // Don't do anything... no data yet.
        CCLOG("No values!");
    }
    else {
        //std::map<int, int> map = *mappointer;

        std::string stringKey, stringValue;
        int key, value;

        CCLOG("COUNT_KEYS: %d", COUNT_KEYS);

        for (int i = 0; i < COUNT_KEYS; i++) {
            stringKey = keys[i];
            stringValue = values[i];

            if (stringKey.length() == 0) {
                CCLOGERROR("length of key was 0!");
                continue;
            }
            if (stringValue.length() == 0) {
                CCLOGERROR("length of value was 0!");
                continue;
            }
            CCLOG("stringKey: '%s' (length: %lu), stringValue: '%s' (length: %lu)", stringKey.c_str(), stringKey.length(), stringValue.c_str(), stringValue.length());

            key = std::stoi(stringKey);
            value = std::stoi(stringValue);

            (*mappointer)[key] = value;

            CCLOG("key %d has value %d", key, (*mappointer)[key]);
        }
    }
}
```

I guess following your advice above on how to save int vectors could be an improvement. Also supporting stuff other than ints by generic coding? And best of all, don't use two keys, but bundle both keys and data inside a two-sized internal vector and just have user enter one key for one map.

**Comment by IgorVovk** [comment]
The problem of NSCoder on C++ is that there is no base class, so I have to write code for saving/loading each variable type. NSArray or NSDictionary had implemened initWithCoder/encodeWithCoder functions inside but std::vector hasn't. Categories in C++ is just inherited class, so you can create MyVector inherited from std::vector and CCNSCoder if you want so. Though it is not very good practice, I decided to create save/load methods for most of scalar types: vector<int>, vector<double>, vectorstd::string I think with minor efforts you can adjust any of your data structure to be of such types. In future I planning to extend with new types: map, list, pair, etc. 

CCNSCoder really trying to follow API of NSCoding. Originally CCNSCoder was written for the game I translated from cocos2d to cocos2dx (objc to c++), original code was created by other developer and it contain complex saving system based on NSCoding. I spent about 2 weeks on it but it started to work properly! This game is RAVENMARK: Scourge of Estellion, so you can estimate how much complex saving system it has.

Since this time I'm using CCNSCoder for about 2.5 years and for now I got no problems with it, it is enough flexible to cover all my needs. Only thing is encoding, I just want to get some encoding library (or implement any encoding algorithm myself) and add one boolean variable to save function. So if you need you can use encoding or save to plain JSON.

Thanks.
